### ISSUE TITLE
AlecrimCoreData 4 with Swift 2 support

### ISSUE THREAD

**Issue by kingslay** [Alecrim/AlecrimCoreData#60] opened 2015-06-17 08:39 UTC
can support swift2.0?

**Comment by vmartinelli** [comment] 2015-06-17 22:23
The winter is... Oops... AlecrimCoreData version 4 is coming with Swift 2 support and many other improvements. And it will come with a rewritten and greatly improved context management. Expect many new protocols  too (instead classes everywhere).

However, even with the new features and code style changes due to the Swift 2, you should not need to make big changes in your existing code.

Soon. :-)

**Comment by ert4i** [comment] 2015-07-16 12:47
Is there any branch where can be 4.0 development version downloaded?

**Comment by vmartinelli** [comment] 2015-07-17 16:49
The Swift language became usable for production, I believe, after version 1.2. All projects that I tried before the launch of this Swift version had to be postponed, due to the large amount of change or workarounds needed, until the language becomes more stable. It looks like the Swift 2 will be ready the first time in its release. But we're still in beta.

Version 4 of AlecrimCoreData is being developed and tested internally. Once I feel that there will be no more big changes in Swift language, I will make public the version 4 branch. I hope to be able to do this very soon.

**Comment by basememara** [comment] 2015-07-18 14:08
Thanks for the updates and insight. I imagine protocol extensions is going to make the attributes, queries, and other source code beautiful :D

**Comment by vmartinelli** [comment] 2015-07-18 17:45
For sure. [POP](https://www.youtube.com/watch?v=xVkU8dDSC9w)* goes my heart! :-)

*Protocol Oriented Programming

**Comment by ert4i** [comment] 2015-07-19 08:01
I just want to mention that we can help with implementing the changes for "changable" swift 2. 
If this would not be a "master" branch then I think it's only understandable that things may not work and are bound to change. Waiting here for your release :) currently I can't help because I don't even know the architecture of 4.0 version. 

BTW - I think tha POP is kind of a scamm :) so really looking if you would be able to implement this in a manner that have obvious benefits VS the OOP approach.

**Comment by basememara** [comment] 2015-07-19 11:26
That sounds like a good idea, even if it doesn't compile. Maybe even making the name of the branch even more explicit like "unready". If the branch is up, not only will it hopefully encourage collaboration on the v4 version, but perhaps feed breakthoughs or upgrade paths back to the main branch.

PS -- dude, if POP doesn't blow your mind you're definitely [missing something](http://www.raywenderlich.com/109156/introducing-protocol-oriented-programming-in-swift-2). It's resolves multiple inheritance without the baggage and provides vast extensibility with minimal impact.

**Comment by ert4i** [comment] 2015-07-19 14:58
Have this read: http://faq.sealedabstract.com/structs_or_classes/

And share your thoughts.

**Comment by vmartinelli** [comment] 2015-07-19 20:26
Well... 

--

Short version:

About the "Structs x Classes x Protocols" discussion, very good articles. Thank you, guys. :-)

Divergent views are great and I wish that many people could read your reviews here and also the mentioned articles to take their own conclusions too.

I hope to make public the ACD4 development version until the end of this month, but it is not a promise. Rather, it is a possibility.

--

Long version:

About the "Structs x Classes x Protocols" discussion, very good articles. Thank you, guys. :-)

I believe that hammer, screwdriver and pliers exist for a reason and each has its purpose and function. Swift and other languages have several tools. Each is good or bad depending on usage (even the language itself). Languages come and go, but nothing replaces having solid fundamentals of software development and programming architecture. I do not think it is "all or nothing". Some do it, they believe the new pattern of the moment should be used everywhere, even where there is no place to use it.

About the protocols (and protocol extensions) in Swift, they are very powerful and if they are well used they can take chances and solutions far beyond. As well as classes and structs if well used too. Of course, protocol extensions are more subject to side effects.

My concern is precisely this "all or nothing" thing. I know that many people who are learning to program in a new language or new environment use the style of programming adopted in open source libraries as example. Some libraries in the early Swift were "playground oriented programming" (because the difficulties of the language as it was at the time, developer lack of technical knowledge or even by taste) and until this day I see people programming that way because they think this is the "correct" way to write code in Swift.

Some developers who are considered "gods" between the community do very good things and do very bad things too, but several other programmers can not distinguish between them and follow everything they say. Instead of blindly following, I try to learn and find what I believe is the best way for me. I do not know what is the "correct" way to write a program in Swift or in any other language. I'm learning and I will always be learning. I am not one of these "gods" nor I wish to be. I love to learn and, because this love, I hope to not only learn, but also contribute using what I think I learned. Some may find good things, some may find bad things, but the important thing to find is the movement and the learning of both parties.

About the version 4 of AlecrimCoreData: I'm seeking a balance between the resources used. Also looking to make an architecture that endures to fads while incorporating the very modern and good things from Swift. I use this library (as well as other internal "Alecrim" libraries) on a daily basis. I'm a library user as well and I think it must have a minimum of consistence and usability before going public, even in the this early development stage.

**Comment by vmartinelli** [comment] 2015-07-20 03:04
OK... Classes, structs, protocols and protocol extensions for everyone. :-) 

A sneak peek:

```swift
import AlecrimCoreData
import Cocoa
import CoreData
import Foundation

//
//  AlecrimCoreData.h
//  AlecrimCoreData
//
//  Created by Vanderlei Martinelli on 2014-06-24.
//  Copyright (c) 2014, 2015 Alecrim. All rights reserved.
//

//! Project version number for AlecrimCoreData.
var AlecrimCoreDataVersionNumber: Double
extension NSString : StringType {
}

extension NSManagedObject {
    func inDataContext(dataContext otherDataContext: DataContextType) throws -> Self?
}

extension String : StringType {
}

extension NSManagedObjectContext : DataContextType {
}

prefix func !(left: NSPredicate) -> NSPredicate

prefix func !<A : AttributeType where A.ValueType : BooleanType>(left: A) -> NSComparisonPredicate

func !=<A : NullableAttributeType, V where A.ValueType : Equatable, A.ValueType == V>(left: A, right: V?) -> NSComparisonPredicate

func !=<L : AttributeType, R : AttributeType where L.ValueType : Equatable, L.ValueType == R.ValueType>(left: L, right: R) -> NSComparisonPredicate

func !=<A : AttributeType, V where A.ValueType : Equatable, A.ValueType == V>(left: A, right: V) -> NSComparisonPredicate

func &&(left: NSPredicate, right: NSPredicate) -> NSPredicate

func <<L : AttributeType, R : AttributeType where L.ValueType : Comparable, L.ValueType == R.ValueType>(left: L, right: R) -> NSComparisonPredicate

func <<A : AttributeType, V where A.ValueType : Comparable, A.ValueType == V>(left: A, right: V) -> NSComparisonPredicate

func <<<A : AttributeType, V : ForwardIndexType where A.ValueType == V>(left: A, right: Range<V>) -> NSComparisonPredicate

func <<<A : AttributeType, V where A.ValueType == V>(left: A, right: [V]) -> NSComparisonPredicate

func <=<L : AttributeType, R : AttributeType where L.ValueType : Comparable, L.ValueType == R.ValueType>(left: L, right: R) -> NSComparisonPredicate

func <=<A : AttributeType, V where A.ValueType : Comparable, A.ValueType == V>(left: A, right: V) -> NSComparisonPredicate

func ==<A : AttributeType, V where A.ValueType : Equatable, A.ValueType == V>(left: A, right: V) -> NSComparisonPredicate

func ==<L : AttributeType, R : AttributeType where L.ValueType : Equatable, L.ValueType == R.ValueType>(left: L, right: R) -> NSComparisonPredicate

func ==<A : NullableAttributeType, V where A.ValueType : Equatable, A.ValueType == V>(left: A, right: V?) -> NSComparisonPredicate

func ><L : AttributeType, R : AttributeType where L.ValueType : Comparable, L.ValueType == R.ValueType>(left: L, right: R) -> NSComparisonPredicate

func ><A : AttributeType, V where A.ValueType : Comparable, A.ValueType == V>(left: A, right: V) -> NSComparisonPredicate

func >=<L : AttributeType, R : AttributeType where L.ValueType : Comparable, L.ValueType == R.ValueType>(left: L, right: R) -> NSComparisonPredicate

func >=<A : AttributeType, V where A.ValueType : Comparable, A.ValueType == V>(left: A, right: V) -> NSComparisonPredicate

protocol Aggregable : Queryable {
    var dataContext: DataContextType { get }
    var entityDescription: NSEntityDescription { get }
}

extension Aggregable {
    func count() -> Int
}

extension Aggregable {
    func any() -> Bool
    func some() -> Bool
    func none() -> Bool
}

extension Aggregable {
    func toFetchRequest() -> NSFetchRequest
}

struct Attribute<T> : AttributeType, NamedAttributeType {
    let ___name: String
    init(_ name: String)
    init(_ name: String, _ parentAttribute: NamedAttributeType)
}

extension Attribute where T : CollectionType {
    var count: AlecrimCoreData.Attribute<Int> { get }
}


/// An attribute that has a name, an associated value type and that can not be compared to nil.
protocol AttributeType : NamedAttributeType {

    /// The associated value type.
    typealias ValueType
}



extension AttributeType where Self.ValueType : Equatable {
    func isEqualTo(value: Self.ValueType) -> NSComparisonPredicate
    func isEqualTo<T : AttributeType where T.ValueType == Self.ValueType>(otherAttribute: T) -> NSComparisonPredicate
    func isNotEqualTo(value: Self.ValueType) -> NSComparisonPredicate
    func isNotEqualTo<T : AttributeType where T.ValueType == Self.ValueType>(otherAttribute: T) -> NSComparisonPredicate
}

extension AttributeType where Self.ValueType : Comparable {
    func isGreaterThan(value: Self.ValueType) -> NSComparisonPredicate
    func isGreaterThan<T : AttributeType where T.ValueType == Self.ValueType>(otherAttribute: T) -> NSComparisonPredicate
    func isGreaterThanOrEqual(value: Self.ValueType) -> NSComparisonPredicate
    func isGreaterThanOrEqual<T : AttributeType where T.ValueType == Self.ValueType>(otherAttribute: T) -> NSComparisonPredicate
    func isLessThan(value: Self.ValueType) -> NSComparisonPredicate
    func isLessThan<T : AttributeType where T.ValueType == Self.ValueType>(otherAttribute: T) -> NSComparisonPredicate
    func isLessThanOrEqual(value: Self.ValueType) -> NSComparisonPredicate
    func isLessThanOrEqual<T : AttributeType where T.ValueType == Self.ValueType>(otherAttribute: T) -> NSComparisonPredicate
}

extension AttributeType where Self.ValueType : StringType {
    func isLike(value: Self.ValueType) -> NSComparisonPredicate
}

extension AttributeType {
    func isIn(values: [Self.ValueType]) -> NSComparisonPredicate
}

extension AttributeType where Self.ValueType : ForwardIndexType {
    func isBetween(range: Range<Self.ValueType>) -> NSComparisonPredicate
}

extension AttributeType where Self.ValueType : BooleanType {
    func not() -> NSComparisonPredicate
}

extension AttributeType where Self.ValueType : StringType {
    func contains(value: Self.ValueType) -> NSComparisonPredicate
    func contains<T : AttributeType where T.ValueType == Self.ValueType>(otherAttribute: T) -> NSComparisonPredicate
    func beginsWith(value: Self.ValueType) -> NSComparisonPredicate
    func beginsWith<T : AttributeType where T.ValueType == Self.ValueType>(otherAttribute: T) -> NSComparisonPredicate
    func endsWith(value: Self.ValueType) -> NSComparisonPredicate
    func endsWith<T : AttributeType where T.ValueType == Self.ValueType>(otherAttribute: T) -> NSComparisonPredicate
}

extension AttributeType where Self.ValueType : StringType {
    func matches(regularExpressionString: String) -> NSComparisonPredicate
}

extension AttributeType where Self.ValueType : CollectionType {
    func any(predicateClosure: (Self.ValueType.Generator.Element.Type) -> NSComparisonPredicate) -> NSComparisonPredicate
    func some(predicateClosure: (Self.ValueType.Generator.Element.Type) -> NSComparisonPredicate) -> NSComparisonPredicate
    func all(predicateClosure: (Self.ValueType.Generator.Element.Type) -> NSComparisonPredicate) -> NSComparisonPredicate
    func none(predicateClosure: (Self.ValueType.Generator.Element.Type) -> NSComparisonPredicate) -> NSPredicate
}

class DataContext : NSManagedObjectContext {
    required init(concurrencyType: NSManagedObjectContextConcurrencyType, dataContextOptions: AlecrimCoreData.DataContextOptions)
    convenience init(dataContextOptions: AlecrimCoreData.DataContextOptions = default)
    convenience init(parentDataContext: AlecrimCoreData.DataContext)
    required init?(coder aDecoder: NSCoder)
}



final class DataContextOptions {
    let managedObjectModelURL: NSURL?
    let persistentStoreURL: NSURL?
    var storeType: AlecrimCoreData.StoreType
    var configuration: String?
    var options: [NSObject : AnyObject]
    var stringComparisonPredicateOptions: NSComparisonPredicateOptions
    init(managedObjectModelURL: NSURL, persistentStoreURL: NSURL)
    init(managedObjectModelURL: NSURL)
    init(persistentStoreURL: NSURL)
    init()
    init(managedObjectModelBundle: NSBundle, applicationGroupIdentifier: String)
    init(managedObjectModelBundle: NSBundle)
    init(applicationGroupIdentifier: String)
}





protocol DataContextType {
    func executeFetchRequest(request: NSFetchRequest) throws -> [AnyObject]
    func countForFetchRequest(request: NSFetchRequest, error: NSErrorPointer) -> Int
    func insertObject(object: NSManagedObject)
    func deleteObject(object: NSManagedObject)
    func refreshObject(object: NSManagedObject, mergeChanges flag: Bool)
}


/// An attribute that has a name.
protocol NamedAttributeType {

    /// This property has undercores as prefix to not conflict with entity property names.
    var ___name: String { get }
}

struct NullableAttribute<T> : NullableAttributeType, AttributeType, NamedAttributeType {
    let ___name: String
    init(_ name: String)
    init(_ name: String, _ parentAttribute: NamedAttributeType)
}


/// An attribute that has a name, an associated value type and that can be compared to nil.
protocol NullableAttributeType : AttributeType {
}

extension NullableAttributeType where Self.ValueType : Equatable {
    func isEqualTo(value: Self.ValueType?) -> NSComparisonPredicate
    func isNotEqualTo(value: Self.ValueType?) -> NSComparisonPredicate
}

protocol Queryable {
    var offset: Int { get set }
    var limit: Int { get set }
    var batchSize: Int { get set }
    var predicate: NSPredicate? { get set }
    var sortDescriptors: [NSSortDescriptor]? { get set }
}

extension Queryable {
    func skip(count: Int) -> Self
    func take(count: Int) -> Self
}

extension Queryable {
    func sortByAttribute(attribute: NamedAttributeType, ascending: Bool = default) -> Self
    func sortByAttributeName(attributeName: String, ascending: Bool = default) -> Self
    func sortUsingSortDescriptor(sortDescriptor: NSSortDescriptor) -> Self
}

extension Queryable {
    func filterUsingPredicate(predicate: NSPredicate) -> Self
}

enum StoreType {
    case SQLite
    case InMemory
}

protocol StringType {
}

struct Table<T : NSManagedObject> : TableType, Aggregable, Queryable {
    let dataContext: DataContextType
    let entityDescription: NSEntityDescription
    var offset: Int
    var limit: Int
    var batchSize: Int
    var predicate: NSPredicate?
    var sortDescriptors: [NSSortDescriptor]?
    init(dataContext: DataContextType)
}

extension Table : SequenceType {
    func generate() -> IndexingGenerator<[T]>
}

protocol TableType : Aggregable, Queryable, SequenceType {
    typealias Entity : NSManagedObject
}

extension TableType {
    func orderByAscending<A : AttributeType, V where A.ValueType == V>(@noescape orderingClosure: (Self.Entity.Type) -> A) -> Self
    func orderByDescending<A : AttributeType, V where A.ValueType == V>(@noescape orderingClosure: (Self.Entity.Type) -> A) -> Self
}

extension TableType {
    func orderBy<A : AttributeType, V where A.ValueType == V>(@noescape orderingClosure: (Self.Entity.Type) -> A) -> Self
    func thenBy<A : AttributeType, V where A.ValueType == V>(@noescape orderingClosure: (Self.Entity.Type) -> A) -> Self
    func thenByAscending<A : AttributeType, V where A.ValueType == V>(@noescape orderingClosure: (Self.Entity.Type) -> A) -> Self
    func thenByDescending<A : AttributeType, V where A.ValueType == V>(@noescape orderingClosure: (Self.Entity.Type) -> A) -> Self
}

extension TableType {
    func filter(@noescape predicateClosure: (Self.Entity.Type) -> NSPredicate) -> Self
}

extension TableType {
    func count(@noescape predicateClosure: (Self.Entity.Type) -> NSPredicate) -> Int
}

extension TableType {
    func any(@noescape predicateClosure: (Self.Entity.Type) -> NSPredicate) -> Bool
    func some(@noescape predicateClosure: (Self.Entity.Type) -> NSPredicate) -> Bool
    func none(@noescape predicateClosure: (Self.Entity.Type) -> NSPredicate) -> Bool
}

extension TableType {
    func first(@noescape predicateClosure: (Self.Entity.Type) -> NSPredicate) -> Self.Entity?
}

extension TableType {
    func first() -> Self.Entity?
}

extension TableType {
    func createEntity() -> Self.Entity
    func deleteEntity(entity: Self.Entity)
    func refreshEntity(entity: Self.Entity, mergeChanges: Bool = default)
}

extension TableType {
    func firstOrCreated(@noescape predicateClosure: (Self.Entity.Type) -> NSComparisonPredicate) -> Self.Entity
}

extension TableType {
    func toArray() -> [Self.Entity]
}

func ||(left: NSPredicate, right: NSPredicate) -> NSPredicate

func ~=<A : AttributeType, V where A.ValueType : StringType, A.ValueType == V>(left: A, right: V) -> NSComparisonPredicate

```

**Comment by ert4i** [comment] 2015-07-20 09:21
vmartinelli 

This "all or nothing" thing is why I'm so skeptical about POP in the first place.

**Comment by basememara** [comment] 2015-07-20 15:29
@vmartinelli nice! Things really cleaned up with the extensions, even the generated models! Really, really liking it :+1: 

@ert4i thx for the article. It had some really harsh criticism which was actually pretty refreshing. I think @vmartinelli hit on something really important (besides "all or nothing" approach)... There are a few players when it comes to programming techniques: 1) the language itself 2) libraries 3) frameworks 4) and finally applications that consume all of the above.

With this in mind...I may be oversimplifying things...but I think it comes down to state vs. no-state. If you have entities coming from the database, then classes make total sense. For utilities, then structs and now protocol-extensions seem like an awesome fit. This is why I think the Apple Swift team is advocating protocol-extensions so much because they are drinking their own kool-aid. Using protocol-extensions in the language itself and its native utilities make absolute total sense and I fully support them going crazy with it. It makes us consumers of the language able to easily extend deep parts of the core language without getting invasive.

For frameworks and applications, this where things get really complicated and become a mixture of states, no-states, utilities, helpers, etc. A balance as @vmartinelli mentioned is key for a framework like ACD since there are so many layers with different roles. Managing state adds a whole other dimension that OOP was designed to handle. POP is a brilliant idea to handle (almost) everything else.

**Comment by vmartinelli** [comment] 2015-07-24 00:45
WIP is now available on `v4_swift2` branch. :D

**Comment by basememara** [comment] 2015-07-25 13:14
Thanks for this.. the code is very very clean and lots of nice rafactoring!! Great work!

**Comment by vmartinelli** [comment] 2015-07-26 19:02
Thank you. Now we can start writing the framework as it would be since the first version. :-)

**Comment by mikevbaker** [comment] 2015-09-04 16:32
I'm in the process of trying to convert a project from Xcode 6 to 7. I grabbed the 'develop' branch and built the framework for iOS. The ACDGen tool fails with "an unspecified error has occurred".
Have you tried Xcode 7 beta 6 yet? Do you have a new ACDGen?

Thanks so much. This is a fantastic tool :)

**Comment by vmartinelli** [comment] 2015-09-05 22:12
@mikevbaker Thank you. :-) About using the framework, The `release/4.0-beta.1` branch will be merged soon. Meanwhile you can use the source from this branch when compiling with Xcode 7 and Swift 2. Please try again and let me know if you have success.

**Comment by vmartinelli** [comment] 2015-09-05 22:15
@mikevbaker Update: it was merged into `develop` branch now.

**Closed** 2015-09-29 15:49 UTC
Labels: enhancement
